source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import register_view, UserDetailView, UserInfoChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/edit/', UserInfoChangeView.as_view(), name = 'user_edit'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='user_profiles', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Фото пользователя')


    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import widgets

from accounts.models import Profile


class UserCreationForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Username', required=True)
    password = forms.CharField(label='Пароль', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput, strip=False)
    email = forms.EmailField(label='Email', required=True)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')
        return password_confirm

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists',
                                  code='user_email_exists')
        except User.DoesNotExist:
            return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('User with this username already exists',
                                  code = 'user_username_exists')
        except User.DoesNotExist:
            return username

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'email']


class UserChangeForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, label='First name', required=False)
    last_name = forms.CharField(max_length=100, label='Last name', required=False)
    avatar = forms.ImageField(label='User pic', required=False)
    email = forms.EmailField(label='Email', required=True)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.user_profiles, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.user_profiles = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        user_profiles, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(user_profiles, field, self.cleaned_data.get(field))
        if not user_profiles.avatar:
            user_profiles.avatar = None

        if commit:
            user_profiles.save()
        return user_profiles

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar']
        profile_fields = ['avatar']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email', 'avatar': 'Фото пользователя'}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label='New Password', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Confirm new Password', widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label='Old Password', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Old password is incorrect!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, UpdateView
from accounts.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from accounts.models import Profile


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data['username'],
                # first_name=form.cleaned_data['first_name'],
                # last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email']
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:index')
    else:
        form = UserCreationForm()
    return render(request, 'create_user.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserInfoChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_info_change.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk':self.object.pk})


class UserPasswordChangeView(UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/create_user.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center font-weight-bold">Регистрация</h1>
    <form action="{% url 'accounts:register' %}" method="post" class="text-center">
        {% include 'partial/form.html' with button_text='Создать' %}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ user_obj.username }}{% endblock %}

{% block menu %}
{% if user_obj == request.user %}
        <li class="nav-item ml-3 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url "accounts:user_edit" user_obj.pk %}">Редактировать</a></li>
        <li class="nav-item ml-3 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личный кабинет: {{ user_obj.username }}</h1>
    {% if user_obj.user_profiles.avatar %}
        <img class="avatar" src="{{ user_obj.user_profiles.avatar.url }}" alt="user picture">
    {% else %}
        <img class="avatar" src="{% static "default-avatar.jpg" %}" alt="No avatar!" />
    {% endif %}
    <p>Имя: <b>{{ user_obj.first_name }}</b></p>
    <p>Фамилия: <b>{{ user_obj.last_name }}</b></p>
    <p>Email: <b>{{ user_obj.email }}</b></p>

{% endblock %}

source/accounts/templates/user_info_change.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}

{% block menu %}
{% if user_obj == request.user %}
    <li class="nav-item pl-5 ml-5"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:user_detail' user_obj.pk %}">Просмотр</a></li>
    <li class="nav-item ml-4 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:password_change' user_obj.pk%}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}

    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_edit' user_obj.pk %}" method="post"
          enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Edit" %}
    </form>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item pl-5 ml-5"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:user_detail' user_obj.pk %}">Просмотр</a></li>
        <li class="nav-item pl-5 ml-5"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:user_edit' user_obj.pk %}">Редактирование профиля</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Поменять пароль: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:password_change' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Сохранить" %}
    </form>
{% endblock %}