source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import register_view, UserDetailView, UserInfoChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/edit/', UserInfoChangeView.as_view(), name = 'user_edit'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views.service_views import IndexView, ServicesView, ServicesCreateView, ServicesEditView, ServicesDeleteView
from webapp.views.review_views import ReviewForServiceCreateView, ReviewEditView, ReviewDeleteView


app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('services/<int:pk>', ServicesView.as_view(), name='service_detail'),
    path('services/create', ServicesCreateView.as_view(), name='service_create'),
    path('services/<int:pk>/edit/', ServicesEditView.as_view(), name='service_edit'),
    path('services/delete/<int:pk>/', ServicesDeleteView.as_view(), name='service_delete'),
    path('services/<int:pk>/add-review/', ReviewForServiceCreateView.as_view(), name='review_create'),
    path('comment/<int:pk>/edit/', ReviewEditView.as_view(), name='review_update'),
    path('comment/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),

]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


CATEGORY_CHOICES = (
    ('other', 'Другое'),
    ('individuals', 'Физические лица'),
    ('legal entities', 'Юридические лица'),
    ('сard service', 'Карточное обслуживание'),
    ('internet banking', 'Интернет банкинг'),
)


class Services(models.Model):
    name = models.CharField(max_length=200, verbose_name='Услуги')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория')
    photo = models.ImageField(upload_to='product_images', null=True, blank=True, verbose_name='Фото')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    def average(self):
        ratings = Review.objects.filter(service=self.pk)
        count = 0
        for rating in ratings:
            count += rating.rating
        try:
            rating_average = count / len(ratings)
            rating_average = round(rating_average, 1)
        except ZeroDivisionError:
            rating_average = 'Нет оценки'

        return rating_average

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


REVIEW_CHOICES = (
    (5, 'excellent'),
    (4, 'good'),
    (3, 'so-so'),
    (2, 'bad'),
    (1, 'awfully')
)


class Review(models.Model):
    author = models.ForeignKey(User, related_name='user_review', on_delete=models.PROTECT, verbose_name='Автор')
    service = models.ForeignKey('webapp.Services', related_name='service_review', on_delete=models.CASCADE,
                                    verbose_name='Услуга')
    text = models.TextField(max_length=1000, verbose_name='Текст отзыва')
    rating = models.IntegerField(choices=REVIEW_CHOICES, verbose_name='Оценка')

    def __str__(self):
        return str(self.author_id)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms
from webapp.models import Review


class ServiceReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.shortcuts import  get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from webapp.forms import ServiceReviewForm
from webapp.models import Review, Services


class ReviewForServiceCreateView(CreateView):
    template_name = 'review/create.html'
    form_class = ServiceReviewForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Services.objects.get(pk=self.kwargs['pk'])
        context['services'] = services
        return context

    def form_valid(self, form):
        services_pk = self.kwargs.get('pk')
        services = get_object_or_404(Services, pk=services_pk)
        services.service_review.create(author=self.request.user, **form.cleaned_data)
        return redirect('webapp:service_detail', pk=services_pk)


class ReviewEditView(PermissionRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Review
    template_name = 'review/edit.html'
    form_class = ServiceReviewForm
    context_object_name = 'review'
    permission_required = 'webapp.change_review'
    permission_denied_message = "Доступ запрещен!"

    def test_func(self):
        review_pk = self.kwargs.get('pk')
        review = Review.objects.get(pk=review_pk)
        return self.request.user == review.author or self.request.user.has_perm('webapp.change_review')

    def get_success_url(self):
        return reverse('webapp:service_detail', kwargs={'pk': self.object.service.pk})


class ReviewDeleteView(PermissionRequiredMixin,UserPassesTestMixin, DeleteView):
    model = Review
    permission_required = 'webapp.delete_review'
    permission_denied_message = "Доступ запрещен!"

    def test_func(self):
        review_pk = self.kwargs.get('pk')
        review = Review.objects.get(pk=review_pk)
        return self.request.user == review.author or self.request.user.has_perm('webapp.delete_review')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:service_detail', kwargs={'pk': self.object.service.pk})

source/webapp/views/service_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import reverse, redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ServiceReviewForm
from webapp.models import Services


class IndexView(ListView):
    model = Services
    template_name = 'service/index.html'
    context_object_name = 'services_list'


class ServicesView(DetailView):
    model = Services
    template_name = 'service/detail.html'
    context_object_name = 'services'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ServiceReviewForm
        service_review = context['services'].service_review.order_by('-rating')
        self.paginate_reviews_to_context(service_review, context)
        return context

    def paginate_reviews_to_context(self, reviews, context):
        paginator = Paginator(reviews, 5, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['reviews'] = page.object_list
        context['is_paginated'] = page.has_other_pages()


class ServicesCreateView(PermissionRequiredMixin, CreateView):
    model = Services
    template_name = 'service/create.html'
    fields = ('name', 'category', 'description', 'photo')
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.add_services'
    permission_denied_message = "Доступ запрещен!"


class ServicesEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'service/edit.html'
    model = Services
    fields = ('name', 'category', 'description', 'photo')
    context_object_name = 'services'
    permission_required = 'webapp.change_services'
    permission_denied_message = "Доступ запрещен!"

    def get_success_url(self):
        return reverse('webapp:index')


class ServicesDeleteView(PermissionRequiredMixin, DeleteView):
    model = Services
    template_name = 'service/delete.html'
    context_object_name = 'services'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_services'
    permission_denied_message = 'Доступ запрещен!'

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Questionnaire{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand font-weight-bold" href="{% url 'webapp:index' %}">Отзовик</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-3">
      <li class="nav-item ml-3 mr-3">
        <a class="nav-link font-weight-bolder" href="{% url 'webapp:index' %}">Услуги</a>
      </li>
      <li class="nav-item ml-3 mr-3">
        <a class="nav-link font-weight-bolder" href="">Отзывы</a>
      </li>

    {% block menu %} {% endblock %}
        {% if request.user.is_authenticated %}
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:user_detail' request.user.pk  %}">Привет, {{ request.user }}!</a></li>
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:logout' %}">Выход</a></li>
        {% else %}
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:login' %}">Вход</a></li>
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'accounts:register' %}">Регистрация</a></li>
        {% endif %}


    </ul>
  </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>
{% block scripts %}
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>